# Generated by Django 5.0.6 on 2024-07-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_district_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='distance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='room',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
