# Generated by Django 5.0.6 on 2024-07-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotels_distance_hotels_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='distance',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
