# Generated by Django 5.0.6 on 2024-07-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_hotels_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
