# Generated by Django 5.0.6 on 2024-07-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_hotels_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('room_sq', models.CharField(max_length=100)),
                ('room_television', models.BooleanField(default=False)),
                ('room_wifi', models.BooleanField(default=True)),
                ('room_bed', models.CharField(max_length=100)),
                ('room_price', models.IntegerField()),
                ('room_view', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='hotels',
            name='rooms',
            field=models.ManyToManyField(blank=True, null=True, to='hotels.hotelroom'),
        ),
    ]
