# Generated by Django 5.0.6 on 2024-07-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_hotelroom_hotels_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='room_image',
            field=models.ManyToManyField(to='hotels.hotelimage'),
        ),
    ]
