# Generated by Django 5.0.6 on 2024-07-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_hotelroom_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='price',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='room',
        ),
        migrations.AlterField(
            model_name='hotels',
            name='rooms',
            field=models.ManyToManyField(to='hotels.hotelroom'),
        ),
    ]
