# Generated by Django 5.0.6 on 2024-07-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_remove_hotels_price_remove_hotels_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='room_booked',
            field=models.BooleanField(default=False),
        ),
    ]
