# Generated by Django 5.0.6 on 2024-07-12 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_hotelreview_created_at_hotelreview_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelreview',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hotelreview',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='hotelreview',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_review', to='hotels.hotels'),
        ),
    ]
