# Generated by Django 5.0.6 on 2024-07-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_address'),
        ('hotels', '0010_hotelroom_room_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ManyToManyField(to='hotels.hotelroom')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='room_booked',
            field=models.ManyToManyField(to='accounts.roombooked'),
        ),
    ]
