# Generated by Django 5.0.6 on 2024-07-10 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_roombooked_profile_room_booked'),
        ('hotels', '0012_alter_hotelroom_room_name_alter_hotelroom_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooked',
            name='room',
        ),
        migrations.AddField(
            model_name='roombooked',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked', to='hotels.hotelroom'),
        ),
    ]
