# Generated by Django 5.0.6 on 2024-07-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_roombooked_room_roombooked_room'),
        ('hotels', '0012_alter_hotelroom_room_name_alter_hotelroom_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooked',
            name='room',
        ),
        migrations.AddField(
            model_name='roombooked',
            name='room',
            field=models.ManyToManyField(to='hotels.hotelroom'),
        ),
    ]
