# Generated by Django 5.0.6 on 2024-07-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='accounts/images/default-profile.png', upload_to='accounts/images/'),
        ),
    ]
